CREATE INDEX "bracket_edges_from_match_id_idx" ON "bracket_edges" USING btree ("from_match_id");--> statement-breakpoint
CREATE INDEX "bracket_edges_to_match_id_idx" ON "bracket_edges" USING btree ("to_match_id");--> statement-breakpoint
CREATE INDEX "entrants_tournament_id_idx" ON "entrants" USING btree ("tournament_id");--> statement-breakpoint
CREATE INDEX "entrants_team_id_idx" ON "entrants" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "group_entries_container_id_idx" ON "group_entries" USING btree ("container_id");--> statement-breakpoint
CREATE INDEX "match_seeds_match_id_idx" ON "match_seeds" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "match_vetos_match_id_idx" ON "match_vetos" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "matches_entrant_a_id_idx" ON "matches" USING btree ("entrant_a_id");--> statement-breakpoint
CREATE INDEX "matches_entrant_b_id_idx" ON "matches" USING btree ("entrant_b_id");--> statement-breakpoint
CREATE INDEX "qualification_results_entrant_id_idx" ON "qualification_results" USING btree ("entrant_id");--> statement-breakpoint
CREATE INDEX "stage_containers_stage_id_idx" ON "stage_containers" USING btree ("stage_id");--> statement-breakpoint
CREATE INDEX "stage_qualifications_source_container_id_idx" ON "stage_qualifications" USING btree ("source_container_id");--> statement-breakpoint
CREATE INDEX "stages_tournament_id_idx" ON "stages" USING btree ("tournament_id");--> statement-breakpoint
CREATE INDEX "tournaments_active_start_date_idx" ON "tournaments" USING btree ("active","start_date");--> statement-breakpoint
CREATE INDEX "news_home_idx" ON "news" USING btree ("show_on_home","status","published_at");--> statement-breakpoint
CREATE INDEX "news_relations_relatable_idx" ON "news_relations" USING btree ("relatable_type","relatable_id");--> statement-breakpoint
CREATE INDEX "logos_entity_idx" ON "logos" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "production_credits_tournament_id_idx" ON "production_credits" USING btree ("tournament_id");--> statement-breakpoint
CREATE INDEX "production_credits_match_id_idx" ON "production_credits" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "team_name_history_team_id_idx" ON "team_name_history" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "map_player_stats_map_id_idx" ON "map_player_stats" USING btree ("map_id");--> statement-breakpoint
CREATE INDEX "map_round_kills_raw_map_round_id_idx" ON "map_round_kills_raw" USING btree ("map_round_id");--> statement-breakpoint
CREATE INDEX "map_round_player_loadouts_raw_map_round_id_idx" ON "map_round_player_loadouts_raw" USING btree ("map_round_id");--> statement-breakpoint
CREATE INDEX "map_rounds_raw_map_id_idx" ON "map_rounds_raw" USING btree ("map_id");--> statement-breakpoint
CREATE INDEX "map_team_round_summary_map_id_idx" ON "map_team_round_summary" USING btree ("map_id");--> statement-breakpoint
CREATE INDEX "map_team_round_summary_entrant_id_idx" ON "map_team_round_summary" USING btree ("entrant_id");--> statement-breakpoint
CREATE INDEX "maps_match_id_idx" ON "maps" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "vods_match_id_idx" ON "vods" USING btree ("match_id");